baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Demo Hugo Site'
theme = "spaced-blog"


sectionPagesMenus = "main"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 20
